#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'fridge_types'


module Color
  BLUE = 1
  RED = 2
  GREEN = 3
  VALUE_MAP = {1 => "BLUE", 2 => "RED", 3 => "GREEN"}
  VALID_VALUES = Set.new([BLUE, RED, GREEN]).freeze
end

class BadColor < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  def initialize(message=nil)
    super()
    self.why = message
  end

  def message; why end

  WHY = 1

  FIELDS = {
    WHY => {:type => ::Thrift::Types::STRING, :name => 'why'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

