#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'list_devices_types'

module ListDevices
  class Client
    include ::Thrift::Client

    def getDevices()
      send_getDevices()
      return recv_getDevices()
    end

    def send_getDevices()
      send_message('getDevices', GetDevices_args)
    end

    def recv_getDevices()
      result = receive_message(GetDevices_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'getDevices failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_getDevices(seqid, iprot, oprot)
      args = read_args(iprot, GetDevices_args)
      result = GetDevices_result.new()
      result.success = @handler.getDevices()
      write_result(result, oprot, 'getDevices', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class GetDevices_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class GetDevices_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRING}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

