#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'camera_types'


module NightvisionStatus
  ON = 1
  OFF = 2
  VALUE_MAP = {1 => "ON", 2 => "OFF"}
  VALID_VALUES = Set.new([ON, OFF]).freeze
end

