#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import camera.ttypes

from thrift.transport import TTransport
all_structs = []


class NightvisionStatus(object):
    ON = 1
    OFF = 2

    _VALUES_TO_NAMES = {
        1: "ON",
        2: "OFF",
    }

    _NAMES_TO_VALUES = {
        "ON": 1,
        "OFF": 2,
    }
fix_spec(all_structs)
del all_structs
